export enum HttpErrors {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_ID = 'INVALID_ID',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  IDS_DONT_MATCH = 'IDS_DONT_MATCH',
  INVALID_DATE_FORMAT = 'INVALID_DATE_FORMAT',
}

export enum WsErrors {
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  GAME_IS_FULL = 'GAME_IS_FULL',
  ALREADY_REGISTERED = 'ALREADY_REGISTERED',
  REGISTRATION_HAS_ENDED = 'REGISTRATION_HAS_ENDED',
  PLAYER_IS_IN_OTHER_GAME = 'PLAYER_IS_IN_OTHER_GAME',
}
