export enum HttpErrors {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_ID = 'INVALID_ID',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  IDS_DONT_MATCH = 'IDS_DONT_MATCH',
  INVALID_DATE_FORMAT = 'INVALID_DATE_FORMAT',
}

export enum GameErrors {
  INVALID_CONNECTION_CREDENTIALS = 'INVALID_CONNECTION_CREDENTIALS',
  GAME_NOT_FOUND = 'GAME_NOT_FOUND',
  MISSING_USER_PAYLOAD = 'MISSING_USER_PAYLOAD',
  PLAYER_NOT_REGISTERED_IN_THIS_GAME = 'PLAYER_NOT_REGISTERED_IN_THIS_GAME',
  INVALID_GAME_ID = 'INVALID_GAME_ID',
  GAME_IS_FULL = 'GAME_IS_FULL',
  PASSWORD_IS_REQUIRED = 'PASSWORD_IS_REQUIRED',
  ALREADY_REGISTERED = 'ALREADY_REGISTERED',
  REGISTRATION_HAS_ENDED = 'REGISTRATION_HAS_ENDED',
  GAME_HAS_ENDED = 'GAME_HAS_ENDED',
  PLAYER_IS_IN_OTHER_GAME = 'PLAYER_IS_IN_OTHER_GAME',
  INVALID_PASSWORD = 'INVALID_PASSWORD',
  UNAUTHORIZED = 'UNAUTHORIZED',
  BAD_REQUEST = 'BAD_REQUEST',
}
